package by.htp.ex.controller;

public enum CommandName {
	
	GO_TO_BASE_PAGE, 
	GO_TO_LOGINATION_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS,
	DO_SIGN_IN, 
	DO_SIGN_OUT,
	GO_TO_ADD_NEWS_PAGE,
	DO_REGISTER,
	GO_TO_EDIT_PAGE,
	SAVE_EDITED_NEWS,
	DELETE_NEWS,
	DELETE_NEWSES,
	ADD_NEWS,
	SWITCH_LOCALE
}